version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install  # Install project dependencies
  build:
    commands:
      - echo "Building the SAM application..."
      - sam build  # Build your SAM project
  post_build:
    commands:
      - echo "Packaging the SAM application..."
      - sam package --output-template-file packaged.yaml --s3-bucket application-s3-fileupload
      - echo "Deploying the SAM application..."
      - sam deploy --template-file packaged.yaml --stack-name serverless-app --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
